--- 
 - name: Printing the variables from the secret.yaml variable file
   hosts: webservers
   vars_files: 
     - secret.yaml
   remote_user: devops
   become: true
   
   tasks: 
     - name: printing the variables
       ansible.builtin.debug:
         msg: "the package name is {{ pkg }} and the service name is {{ srv }}"
