---
# This playbook prints variables from a file (secret.yaml) on the hosts defined in the 'webservers' group
- name: Printing the variables from the secret.yaml variable file
  hosts: webservers  # Target hosts that are part of the 'webservers' group
  vars_files: 
    - secret.yaml  # Load the variables from the 'secret.yaml' file
  remote_user: devops  # The user on the remote machines to execute the playbook
  become: true  # Escalate privileges (e.g., using sudo)

  tasks: 
    - name: printing the variables
      # The debug module is used to print messages to the output
      ansible.builtin.debug:
        # The message printed will include the values of the variables 'pkg' and 'srv'
        msg: "the package name is {{ pkg }} and the service name is {{ srv }}"
